services:
  postgres:
    image: postgres:17-alpine
    container_name: cobros_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - cobros_network


  backend:
    image: ghcr.io/victor1997h/cobros-predictivo-backend:latest
    pull_policy: always

    container_name: cobros_backend
    restart: unless-stopped

    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - cobros_network
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.cobros-backend.rule=Host(`backsistemacobros.byronrm.com`)"
      - "traefik.http.routers.cobros-backend.entrypoints=websecure"
      - "traefik.http.routers.cobros-backend.tls.certresolver=letsencrypt"

      - "traefik.http.services.cobros-backend.loadbalancer.server.port=3000"


  frontend:
    image: ghcr.io/victor1997h/cobros-predictivo-frontend:latest
    pull_policy: always

    container_name: cobros_frontend
    restart: unless-stopped

    depends_on:
      - backend

    networks:
      - cobros_network
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.cobros-frontend.rule=Host(`sistemacobros.byronrm.com`)"
      - "traefik.http.routers.cobros-frontend.entrypoints=websecure"
      - "traefik.http.routers.cobros-frontend.tls.certresolver=letsencrypt"

      - "traefik.http.services.cobros-frontend.loadbalancer.server.port=80"


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cobros_pgadmin
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - cobros_network
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.cobros-pgadmin.rule=Host(`pgsistemacobros.byronrm.com`)"
      - "traefik.http.routers.cobros-pgadmin.entrypoints=websecure"
      - "traefik.http.routers.cobros-pgadmin.tls.certresolver=letsencrypt"

      - "traefik.http.services.cobros-pgadmin.loadbalancer.server.port=80"


volumes:
  postgres_data:
  pgadmin_data:


networks:
  cobros_network:
    driver: bridge

  proxy:
    external: true
